QUIET=
#
# Vala compiler binary
#
VALAC=valac

#
# Program name
#
PROGRAM=sdlmpc

#
# Source files
#
SOURCES=\
	$(wildcard SRC/*.vala)\
	$(wildcard SRC/**/*.vala)

#
# Directory where source files should be dumped
#
SOURCE_DIR=build/sources

#
# Directory where binary is placed
#
BUILD_DIR=build/binary

#
# PKG_CONFIG packages that should be used
#
PKGCONFIG_PACKAGES=\
    glib-2.0\
    sdl\
    SDL_image\
    libmpdclient\

#
# Other vala binding that should be used
#
VALA_PACKAGES=\
    linux\
    sdl-ttf\
    posix

#
# Where extra vapi files are located
#
VAPI_DIR=\
	vapi

##
# Vala Flags
# Manually add -lSDL_ttf, because that seems to be missing.
##
VALA_FLAGS=--thread --Xcc="-lSDL_ttf" --Xcc="-g"

##################################################################################
##          processing above information                                        ##
##################################################################################
OUTPUT=$(BUILD_DIR)/$(PROGRAM)

##
# Make right syntax for vala
##
VALA_PKG=$(foreach p,$(VALA_PACKAGES) $(PKGCONFIG_PACKAGES),--pkg=$p)
VAPI_DIRS=$(foreach p,$(VAPI_DIR), --vapidir=$p)


##
# Check if packages are available
##
PACKAGES_EXISTS=$(shell pkg-config --exists $(PKGCONFIG_PACKAGES); echo $$?)
ifeq ($(PACKAGES_EXISTS),0)
    $(info ** $(PKGCONFIG_PACKAGES) packages found)
else
    $(error One or more packages missing from: $(PKGCONFIG_PACKAGES))
endif



##
# all clause. first one in the chain, so executed
# when no command specified
##
all: $(OUTPUT) 

##
# Create the build dir 
##
$(BUILD_DIR):
	$(info Create '$@' Directory)
	$(QUIET)mkdir -p '$@'
##
# Create the source dir
##
$(SOURCE_DIR):
	$(info Create '$@' Directory)
	$(QUIET)mkdir -p '$@'

##
# Program compilation
##
$(OUTPUT): $(SOURCES) $(BUILD_DIR)
	$(info Building source files: '$(SOURCES)')
	$(QUIET) $(VALAC) -v --save-temps -g -o $(PROGRAM) $(SOURCES)  $(VAPI_DIRS)  $(VALA_PKG) $(VALA_FLAGS) -D PC -d $(BUILD_DIR)

##
# Build source (for compilation on sbt)
##
source:  $(SOURCES) $(SOURCE_DIR)
	$(info Creating source files: '$(SOURCES)')
	$(QUIET) $(VALAC) $(SOURCES)  $(VAPI_DIRS) $(VALA_PKG) $(VALA_FLAGS) -C -d $(SOURCE_DIR)


##
# Run it.
##
.PHONY: run
run: $(OUTPUT)
	$(OUTPUT)

##
# Clean up
##
clean:
	 $(info Removing $(BUILD_DIR) and $(SOURCE_DIR))
	$(QUIET) @rm -rf $(BUILD_DIR) $(SOURCE_DIR)


.PHONY: doc
doc:
	valadoc --package-name=SDLMpc  --force --no-protected --internal --private -b ./ --doclet=html -o doc/api-html *.vala $(VAPI_DIRS) $(VALA_PKG)
